apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  strategy: {}
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - image: "docker.io/alejandroguzman/helloworld:latest"
        imagePullPolicy: Always
        name: helloworld
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
        resources:
          limits:
            memory: "128Mi"
            cpu: "2"
          requests:
            memory: "32Mi"
            cpu: "300m"
status: {}
