version: "3.7"
services:
  mongo:
    image: mongo
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - version=v0.2.0
    environment:
    - MONGO_HOST=mongo
    ports:
    - "8080:8080"
    depends_on:
    - mongo